#!/usr/bin/env python3
"""
Rung 2a - validate LeRobot's Unitree G1 IK stack.

No simulator, no XR headset, no robot hardware. This isolates one failure domain:
the inverse-kinematics stack. Run it before rung 2b so that a MuJoCo failure later
cannot be confused with an IK failure.

Exercises:
  * HuggingFace Hub download of lerobot/unitree-g1-mujoco
  * conda-forge pinocchio + its CasADi bindings (PyPI `pin` has none)
  * the CasADi/IPOPT solve and its residuals
  * Pinocchio-vs-G1 joint ordering
  * the smoothing filter's group delay

Requires:
  conda install -c conda-forge "pinocchio>=3.0.0,<4.0.0"
  pip install -e ".[dataset]" casadi          # NOT [kinematics] - it clobbers pinocchio

Usage:  python rung2a_ik_only.py
"""

import numpy as np
import pinocchio as pin

from lerobot.robots.unitree_g1.g1_kinematics import G1_29_ArmIK

PASS_MM = 3.0        # static residual budget; current LeRobot stack settles around 2.3 mm
SEED = 0


def banner(t):
    print(f"\n{'=' * 62}\n{t}\n{'=' * 62}")


# ----------------------------------------------------------------------------
# Setup
# ----------------------------------------------------------------------------
print("building G1_29_ArmIK (first run downloads lerobot/unitree-g1-mujoco)...")
ik = G1_29_ArmIK()

# G1_29_ArmIK calls buildReducedRobot() -- which creates reduced_robot.data -- and
# only THEN addFrame("L_ee")/addFrame("R_ee"). The shipped data.oMf is therefore
# shorter than model.nframes, and touching the EE frames raises IndexError and then
# segfaults on teardown. Recreate data. (exo_ik.py silently does the same.)
m = ik.reduced_robot.model
d = m.createData()
ik.reduced_robot.data = d

print(f"  reduced model: nq={m.nq} nv={m.nv}   (expect 14/14 for G1-29)")

order_ok = ik._arm_joint_names_g1 == ik._arm_joint_names_pin
print(f"  joint order g1 == pinocchio: {order_ok}")
if not order_ok:
    print("    G1 :", ik._arm_joint_names_g1)
    print("    PIN:", ik._arm_joint_names_pin)
    print("    ^ solve_ik returns q in PINOCCHIO order - reorder before sending to a robot")


def residuals(q, L, R):
    """Pose error at q against targets L, R. Returns (metres, radians)."""
    return (float(np.linalg.norm(np.asarray(ik.translational_error(q, L, R)).ravel())),
            float(np.linalg.norm(np.asarray(ik.rotational_error(q, L, R)).ravel())))


def fk(q):
    pin.forwardKinematics(m, d, q)
    pin.updateFramePlacements(m, d)
    return (d.oMf[ik.L_hand_id].homogeneous.copy(),
            d.oMf[ik.R_hand_id].homogeneous.copy())


L_rest, R_rest = fk(np.zeros(m.nq))
print(f"  L_ee @ q=0: {np.round(L_rest[:3, 3], 4)}")
print(f"  R_ee @ q=0: {np.round(R_rest[:3, 3], 4)}")


# ----------------------------------------------------------------------------
# TEST 1 - static, FK-consistent target.  This is the pass/fail test.
# ----------------------------------------------------------------------------
# Targets are generated by forward kinematics from a real configuration, so an
# exact solution provably EXISTS (it is q_true). Any residual is the solver's.
#
# Do NOT hand-write a target by translating the rest pose while holding its
# original orientation - nothing guarantees such a pose is reachable, and because
# pose is a soft cost rather than a hard constraint the solver will return a
# translation/rotation compromise that looks like a failure but is not.
banner("TEST 1 - static FK-consistent target (exact solution exists)")

rng = np.random.default_rng(SEED)
q_true = rng.uniform(-0.35, 0.35, m.nq)
L, R = fk(q_true)

q = np.zeros(m.nq)
for i in range(14):
    q, tau = ik.solve_ik(L, R, q)
    e_t, e_r = residuals(q, L, R)
    if i in (0, 1, 2, 3, 5, 8, 13):
        print(f"  step {i:2d}   |e_t| = {e_t * 1000:8.4f} mm    |e_r| = {np.degrees(e_r):7.4f} deg")

static_t, static_r = e_t, e_r
print(f"\n  settled          |e_t| = {static_t * 1000:.4f} mm    |e_r| = {np.degrees(static_r):.4f} deg")
print(f"  gravity torque nonzero: {bool(np.any(np.abs(tau) > 1e-6))}")
print(f"  |q - q_true|     = {np.linalg.norm(q - q_true):.4f} rad")
print("  (a nonzero joint-space difference is fine: 7 DoF per arm against a 6-DoF")
print("   task leaves a null space, so a different arm pose can reach the same hand pose)")

# The residual floor is not zero even here: the objective carries
# 0.02*||q||^2, which biases every solution toward the zero configuration.


# ----------------------------------------------------------------------------
# TEST 2 - moving target.  A measurement, not a pass/fail.
# ----------------------------------------------------------------------------
# Residual on a moving target is dominated by the smoothing filter's group delay,
# not by solver error. Reported in STEPS so it is comparable across speeds.
banner("TEST 2 - moving target (measures tracking lag, not correctness)")

N, RAD = 60, 0.05
step_mm = 2 * np.pi * RAD / N * 1000

q = np.zeros(m.nq)
worst = 0.0
for i in range(N):
    a = 2 * np.pi * i / N
    L, R = L_rest.copy(), R_rest.copy()
    off = np.array([0.0, RAD * np.sin(a), RAD * (1.0 - np.cos(a))])
    L[:3, 3] += off
    R[:3, 3] += off
    q, _ = ik.solve_ik(L, R, q)
    if i > 6:                       # let the 4-tap filter window fill first
        worst = max(worst, residuals(q, L, R)[0])

print(f"  target speed     = {step_mm:.2f} mm/step")
print(f"  worst |e_t|      = {worst * 1000:.2f} mm")
print(f"  implied lag      = {worst * 1000 / step_mm:.2f} steps")


# ----------------------------------------------------------------------------
# TEST 3 - the filter itself, no IK involved.
# ----------------------------------------------------------------------------
# WeightedMovingFilter computes np.array(self._data_queue).T @ self._weights.
# The deque is oldest-first, so with weights [0.4, 0.3, 0.2, 0.1] the OLDEST
# sample is weighted 0.4 and the NEWEST 0.1 - double the necessary delay.
banner("TEST 3 - smoothing filter group delay (no IK)")

from lerobot.robots.unitree_g1.g1_kinematics import WeightedMovingFilter  # noqa: E402

w = np.array([0.4, 0.3, 0.2, 0.1])
f = WeightedMovingFilter(w, 1)
lags = []
for i in range(10):
    f.add_data(np.array([float(i)]))
    out = float(f.filtered_data[0])
    if i >= len(w):
        lags.append(i - out)

print(f"  weight on oldest sample : {w[0]}")
print(f"  weight on newest sample : {w[-1]}")
print(f"  measured delay on a ramp: {np.mean(lags):.2f} steps")
print(f"  delay if weights reversed: "
      f"{float(sum((len(w) - 1 - i) * w[::-1][i] for i in range(len(w)))):.2f} steps")
print("  -> at a 30 Hz teleop loop this is ~67 ms of latency where ~33 ms would do")


# ----------------------------------------------------------------------------
banner("RESULT")
ok = static_t * 1000 < PASS_MM
print(f"  static residual {static_t * 1000:.4f} mm  (budget {PASS_MM} mm)")
print(f"  joint ordering  {'consistent' if order_ok else 'MISMATCHED'}")
print()
print("  PASS - the G1 IK stack is working; proceed to rung 2b"
      if ok else
      "  FAIL - static residual too large; the solver is not converging.\n"
      "         Check pinocchio came from conda-forge and has CasADi bindings.")
